defaultSemverRangePrefix: ""

enableScripts: true

nodeLinker: node-modules

enableStrictSsl: false

npmRegistryServer: "https://nexus.services.mts.ru/repository/npm-all/"

npmScopes:
  mts-ds:
    npmRegistryServer: "https://nexus.design.mts.ru/repository/components/"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
