export enum ConnectionType {
  CLICKHOUSE = 'clickhouse',
  FTP = 'ftp',
  FTPS = 'ftps',
  HDFS = 'hdfs',
  HIVE = 'hive',
  MSSQL = 'mssql',
  MYSQL = 'mysql',
  ORACLE = 'oracle',
  POSTGRES = 'postgres',
  SAMBA = 'samba',
  SFTP = 'sftp',
  S3 = 's3',
  WEBDAV = 'webdav',
}
